### ISSUE TITLE
Platform replication

### ISSUE THREAD

**Issue by OmniStage-AI** [mantechnology/bsr#3]
Hello, does the system support cross platform heterogeneous replication?

How to configure it?

thank you!

**Comment by sungeun-kim** [comment]
Hello.

Although heterogeneous operating environments are not recommended, there is no problem.

And, there is no special configuration form. For example, if it is a Windows/Linux replication environment, you only need to configure the resource configuration file in each environment and connect the activated resource between each others.

However, since the file system is different because it is a heterogeneous environment, the file system not supported by each OS cannot be recognized, so HA operation will be impossible.

**Comment by OmniStage-AI** [comment]
Hello, because Linux is configured with a detection device name, the configuration of operating systems on both sides cannot be interconnected. How do I need to configure it?

**Comment by OmniStage-AI** [comment]
Hello, because Linux is configured with a detection device name, the configuration of operating systems on both sides cannot be interconnected. How do I need to configure it?

**Comment by sungeun-kim** [comment]
The device names in the conf files of both nodes must be configured differently. You can configure it roughly as below.

```
resource r0 {
    device	e minor 2; #(linux: device /dev/bsr2)
    disk	e;  #(linux:  /dev/sdc)
    meta-disk f; #(linux: /dev/sdd)
	
on linux_node {
	address 192.168.0.100:7792;
	node-id 0;
}
	
on win_node {
    address	192.168.0.200:7792;
    node-id	1;
 }
  
connection {
	host linux_node;
	host win_node;
}

}
```

**Comment by reinhardvz** [comment]
test comment

**Comment by sungeun-kim** [comment]
test
