### ISSUE TITLE
Long Distance Replication

### ISSUE THREAD

**Issue by darronhrrsn** [mantechnology/bsr#7]
Hey Everyone,

It's an exciting project. I am interested in using this in production. One question: how does this fork of DRBD deal with long-distance replication? Currently, in DRBD, writing is blocked if the send queue fills. Will this project queue changes appropriately, perhaps like DRBD proxy?

Thanks,

Darron

**Comment by sungeun-kim** [comment]
hello

There are two ways to expand the transmission queue in bsr. One is to increase the kernel-side buffer, and the other is to link the proxy.(drbd only supports proxy linking, but bsr has added kernel Tx buffering function.)

and

When the buffer is full (congestion mode), the policy for handling this is separate from expanding the transmission queue.
The default is blocking mode, which blocks writes until the queue is emptied (the mode you mentioned).
If set to Ahead mode, writing continues when the buffer becomes congested and synchronizes after the congestion is cleared. At least writes aren't blocked in this mode.

I hope this helps.

thanks

**Comment by darronhrrsn** [comment]
In Ahead mode, are there limits on how many writes can be buffered? We have a high-performance DRBD cluster with 10Gbe connections to clients and a 1G downlink at that data center. If we were to stack bsr under one protocol A node and replicate to a separate location, do you have any thoughts on writes getting blocked on the bsr node when the cluster is getting hit with 1GB/sec writes?

**Comment by sungeun-kim** [comment]
Since you mentioned the stack method, it looks like you are using DRBD version 8.4.
bsr supports DRBD9-based 1:N replication, but stack replication from 8.4 is no longer supported.

Anyway, I think the core of your question is how to deal with write blocking when replication bandwidth is full.

If the time for the bandwidth to be full is temporary (perhaps within a few seconds), buffering may be sufficient. However, if the I/O is too much to handle even with buffering, you must respond by setting delayed replication (Ahead) to prevent writing from being blocked. When entering Ahead mode after buffer congestion, local writing continues and unsynchronized areas are processed for synchronization after congestion is cleared.
If the I/O load is so large that it cannot be processed by operating in this way, it is judged to be an unsuitable situation for operating through replication. Either separate the I/O load or expand bandwidth.

thank you
